### ISSUE TITLE
`dub test` fails

### ISSUE THREAD

**Issue by pbackus** [libmir/mir-optim#18]
Command:

    $ dub test -c unittest-blas --compiler=dmd

Output:

    The sub configuration directive "mir-lapack" -> "lapack" references a configuration that does not exist.
    The sub configuration directive "mir-lapack" -> "lapack" references a configuration that does not exist.
    Generating test runner configuration 'mir-optim-test-unittest' for 'unittest' (library).
    Performing "unittest" build using dmd for x86_64.
    mir-core 1.1.111: target for configuration "library" is up to date.
    mir-algorithm 3.15.1: building configuration "default"...
    ../../../.dub/packages/mir-algorithm-3.15.1/mir-algorithm/source/mir/annotated.d(10,8): Error: module `mir.internal.meta` import `basicElementType` not found
    ../../../.dub/packages/mir-algorithm-3.15.1/mir-algorithm/source/mir/string_map.d(10,8): Error: module `mir.internal.meta` import `basicElementType` not found
    ../../../.dub/packages/mir-algorithm-3.15.1/mir-algorithm/source/mir/string_map.d(1046,23): Error: `mir.string_map.basicElementType` is not a template, it is a alias
    ../../../.dub/packages/mir-algorithm-3.15.1/mir-algorithm/source/mir/algebraic_alias/ion.d(49,5): Error: template instance `mir.string_map.StringMap!(This)` error instantiating
    ../../../.dub/packages/mir-algorithm-3.15.1/mir-algorithm/source/mir/annotated.d(123,23): Error: `mir.annotated.basicElementType` is not a template, it is a alias
    ../../../.dub/packages/mir-algorithm-3.15.1/mir-algorithm/source/mir/algebraic_alias/ion.d(51,5): Error: template instance `mir.annotated.Annotated!(This)` error instantiating
    dmd failed with exit code 1.
    
Using DMD version 2.100.2. Same failure occurs on `v2.0.1` (latest dub release) and `master`.

Since this project is included in D's project tester, this failure is blocking PRs to core D repositories.

**Comment by 9il** [comment]
Thank you. Fixed by the new colas release
